[meta]
path = "assets/ss_player_rgba.tga"
format = "RGBA8888"
scale = 4
width = 80
height = 16

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 0
y = 0
w = 16
h = 16

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 16
y = 0
w = 16
h = 16

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 32
y = 0
w = 16
h = 16

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 48
y = 0
w = 16
h = 16

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 64
y = 0
w = 16
h = 16
