[meta]
path = "assets/ss_skelly.tga"
format = "RGBA8888"
scale = 1
width = 160
height = 30

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 0
y = 0
w = 32
h = 30

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 32
y = 0
w = 32
h = 30

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 64
y = 0
w = 32
h = 30

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 96
y = 0
w = 32
h = 30

[[frames]]
rotated = false
trimmed = false
duration = 100.0
x = 128
y = 0
w = 32
h = 30
