[meta]
path = "assets/image/ss_player_rgba.tga"
format = "RGBA8888"
scale = 2
width = 80
height = 16

[[frames]]
rotated = false
trimmed = false
duration = 0.100
x = 0
y = 0
w = 16
h = 16

[[frames]]
rotated = false
trimmed = false
duration = 0.100
x = 16
y = 0
w = 16
h = 16

[[frames]]
rotated = false
trimmed = false
duration = 0.100
x = 32
y = 0
w = 16
h = 16

[[frames]]
rotated = false
trimmed = false
duration = 0.100
x = 48
y = 0
w = 16
h = 16

[[frames]]
rotated = false
trimmed = false
duration = 0.100
x = 64
y = 0
w = 16
h = 16
